# Generated by Django 3.1.5 on 2021-01-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='PostModel',
            new_name='Post',
        ),
    ]
